config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get root                        to: 'home#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: [:show] do
      collection do
        get 'search'
      end
    end
    resources :categories, only: [:show]
    resources :orders, only: [:show]
    get 'cart', to: 'orders#edit'
    post 'add_cart', to: 'orders#add_cart'
    patch 'cart', to: 'orders#update'
    resources :line_items, only: [:destroy]
    get 'checkout/:state', to: 'checkout#edit', as: :checkout_state
    patch 'checkout/update/:state', to: 'checkout#update', as: :update_checkout
    devise_for :spree_users, {
      class_name: 'Spree::User', controllers: {
        sessions: 'potepan/user_sessions',
        registrations: 'potepan/user_registrations',
      },
    }
    devise_scope :spree_user do
      get '/logout', to: 'user_sessions#destroy', as: :logout
      post '/login', to: 'user_sessions#create', as: :create_new_session
      post '/signup', to: 'user_registrations#create', as: :registration
    end
  end
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  # Viewでcount_number_of_productsメソッドを使えるようにする
  helper_method :count_number_of_products

  def show
    # includesで「N+1問題」を解決
    # SELECT `taxonomies`.* FROM `taxonomies` WHERE `taxonomies`.`root_id` IN (1, 2, 3, ...)
    @taxonomies = Spree::Taxonomy.includes(:root)

    @taxon = Spree::Taxon.find(params[:id])

    @option_types = Spree::OptionType.includes(:option_values)

    @products =
      if params[:color] && params[:sort]
        Spree::Product.select_by_category(@taxon).
          filter_by_option_values(filter_params[:color]).
          sort_in_order(filter_params[:sort])
      elsif params[:size] && params[:sort]
        Spree::Product.select_by_category(@taxon).
          filter_by_option_values(filter_params[:size]).
          sort_in_order(filter_params[:sort])
      elsif params[:color] && params[:size]
        colors_ids = Spree::Product.
          select_by_category(@taxon).
          filter_by_option_values(filter_params[:color]).ids
        sizes_ids = Spree::Product.
          select_by_category(@taxon).
          filter_by_option_values(filter_params[:size]).ids
        Spree::Product.where(id: colors_ids & sizes_ids)
      elsif params[:color]
        Spree::Product.select_by_category(@taxon).
          filter_by_option_values(filter_params[:color])
      elsif params[:size]
        Spree::Product.select_by_category(@taxon).
          filter_by_option_values(filter_params[:size])
      elsif params[:sort]
        Spree::Product.select_by_category(@taxon).
          sort_in_order(filter_params[:sort])
      else
        Spree::Product.select_by_category(@taxon).
          from_newest_to_oldest
      end
  end

  private

  # URLクエリをストロングパラメーターで取得
  def filter_params
    { color: params[:color], size: params[:size], sort: params[:sort] }
  end

  # Color, Sizeなどのoption_valueに応じた商品数を取得するメソッド
  def count_number_of_products(option_value)
    Spree::Product.includes(variants: :option_values).
      in_taxon(@taxon).
      where(spree_option_values: { name: option_value }).
      count
  end
end

app/controllers/potepan/checkout_controller.rb
class Potepan::CheckoutController < ApplicationController
  include Spree::Core::ControllerHelpers::StrongParameters
  include Spree::Core::ControllerHelpers::PaymentParameters
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  before_action :load_order
  before_action :set_state_if_present
  before_action :setup_for_current_state, only: [:edit, :update]

  # Updates the order and advances to the next state (when possible.)
  def update
    if update_order
      unless transition_forward
        redirect_on_failure
        return
      end

      if @order.completed?
        finalize_order
      else
        @order.next if @order.state == "delivery"
        send_to_next_state
      end

    else
      render :edit
    end
  end

  private

  def update_order
    Spree::OrderUpdateAttributes.new(@order, update_params, request_env: request.headers.env).apply
  end

  def redirect_on_failure
    flash[:error] = @order.errors.full_messages.join("\n")
    redirect_to(potepan_checkout_state_path(@order.state))
  end

  def transition_forward
    if @order.can_complete?
      @order.complete
    else
      @order.next
    end
  end

  def finalize_order
    @current_order = nil
    Spree::OrderMailer.confirm_email(@order).deliver_now
    set_successful_flash_notice
    redirect_to completion_route
  end

  def set_successful_flash_notice
    flash.notice = t('spree.order_processed_successfully')
    flash['order_completed'] = true
  end

  def send_to_next_state
    redirect_to potepan_checkout_state_path(@order.state)
  end

  def update_params
    if update_params = massaged_params[:order]
      update_params.permit(permitted_checkout_attributes)
    else
      # We currently allow update requests without any parameters in them.
      {}
    end
  end

  def massaged_params
    massaged_params = params.deep_dup

    move_payment_source_into_payments_attributes(massaged_params)
    if massaged_params[:order] && massaged_params[:order][:existing_card].present?
      Spree::Deprecation.
      warn("Passing order[:existing_card] is deprecated. Send order[:wallet_payment_source_id] instead.", caller)
      move_existing_card_into_payments_attributes(massaged_params) # deprecated
    end
    move_wallet_payment_source_id_into_payments_attributes(massaged_params)
    set_payment_parameters_amount(massaged_params, @order)

    massaged_params
  end

  # Should be overriden if you have areas of your checkout that don't match
  # up to a step within checkout_steps, such as a registration step
  def skip_state_validation?
    false
  end

  # @orderがない場合、カートページに遷移
  def load_order
    @order = current_order
    redirect_to(potepan_cart_path) && return unless @order
  end

  # params[:state]がある場合、次のステップへ進む
  def set_state_if_present
    if params[:state]
      redirect_to potepan_checkout_state_path(@order.state) if @order.can_go_to_state?(params[:state]) && !skip_state_validation?
      @order.state = params[:state]
    end
  end

  # Provides a route to redirect after order completion
  def completion_route
    potepan_order_path(@order)
  end

  def setup_for_current_state
    method_name = :"before_#{@order.state}"
    send(method_name) if respond_to?(method_name, true)
  end

  def before_address
    @order.assign_default_user_addresses
    # If the user has a default address, the previous method call takes care
    # of setting that; but if he doesn't, we need to build an empty one here
    default = { country_id: Spree::Country.default.id }
    @order.build_ship_address(default) unless @order.ship_address
  end

  def before_delivery
    return if params[:order].present?

    packages = @order.shipments.map(&:to_package)
    @differentiator = Spree::Stock::Differentiator.new(@order, packages)
  end

  def before_payment
    if @order.checkout_steps.include? "delivery"
      packages = @order.shipments.map(&:to_package)
      @differentiator = Spree::Stock::Differentiator.new(@order, packages)
      @differentiator.missing.each do |variant, quantity|
        @order.contents.remove(variant, quantity)
      end
    end

    if try_spree_current_user && try_spree_current_user.respond_to?(:wallet)
      @wallet_payment_sources = try_spree_current_user.wallet.wallet_payment_sources
      @default_wallet_payment_source = @wallet_payment_sources.detect(&:default) ||
                                       @wallet_payment_sources.first

      # TODO: How can we deprecate this instance variable?  We could try
      # wrapping it in a delegating object that produces deprecation warnings.
      @payment_sources = try_spree_current_user.wallet.wallet_payment_sources.
        map(&:payment_source).
        select { |ps| ps.is_a?(Spree::CreditCard) }
    end
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  NEW_PRODUCTS_LIMIT = 8

  def index
    # new_products scopeは、app/models/spree/product_decoratorにて定義
    @new_products = Spree::Product.includes(master: [:default_price, :images]).
      from_newest_to_oldest.limit(NEW_PRODUCTS_LIMIT)
  end
end

app/controllers/potepan/line_items_controller.rb
class Potepan::LineItemsController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def destroy
    item = Spree::LineItem.find(params[:id])
    item.order.contents.remove_line_item(item)
    redirect_to potepan_cart_path
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def show
    @order = Spree::Order.find_by(number: params[:id])
  end

  def edit
    # https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/orders_controller.rb
    @order = current_order || Spree::Order.incomplete.
      find_or_initialize_by(guest_token: cookies.signed[:guest_token])
  end

  def add_cart
    # 新しいアイテムをカートに追加
    # https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/orders_controller.rb
    @order = current_order(create_order_if_necessary: true)
    authorize! :update, @order, cookies.signed[:guest_token]

    variant  = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].to_i

    # あり得ない量が注文されてエラーが起きる防ぐために 発注の最大値を設定する
    if !quantity.between?(1, 2_147_483_647)
      @order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
    end

    # カートのアップデート時にエラーが起こった場合に、500エラーを吐かせ図にメッセージを返す
    begin
      @line_item = @order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => e
      @order.errors.add(:base, e.record.errors.full_messages.join(", "))
    end

    if @order.errors.any?
      flash[:error] = @order.errors.full_messages.join(", ")
      redirect_back_or_default potepan_root_path
      return
    else
      redirect_to potepan_cart_path
    end
  end

  def update
    @order = Spree::Order.find_by(number: params[:number])
    if @order.contents.update_cart(order_params)
      # formの送信先のnameがcheckoutの場合、次ステップに進む
      @order.next if params.key?(:checkout) && @order.cart?
      if params.key?(:checkout)
        redirect_to potepan_checkout_state_path(@order.checkout_steps.first)
      else
        redirect_to potepan_cart_path
      end
    end
  end

  private

  def order_params
    params.require(:order).permit(line_items_attributes: [:id, :quantity])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  RELATED_PRODUCTS_LIMIT = 4

  def show
    @product = Spree::Product.find(params[:id])

    # related_products scopeは、app/models/spree/product_decoratorにて定義
    @related_products = Spree::Product.related_products(@product).limit(RELATED_PRODUCTS_LIMIT)
  end

  def search
    @search_word = params[:search]
    @products = Spree::Product.search(@search_word)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/user_registrations_controller.rb
class Potepan::UserRegistrationsController < Devise::RegistrationsController
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Common
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Store

  def create
    build_resource(spree_user_params)
    if resource.save
      set_flash_message(:success, :signed_up)
      sign_in(:spree_user, resource)
      session[:spree_user_signup] = true
      respond_with resource, location: after_sign_up_path_for(resource)
    else
      clean_up_passwords(resource)
      respond_with(resource) do |format|
        flash[:error] = t('devise.failure.invalid')
        format.html { redirect_to potepan_root_path }
      end
    end
  end

  private

  def spree_user_params
    params.require(:spree_user).permit(Spree::PermittedAttributes.user_attributes | [:email])
  end
end

app/controllers/potepan/user_sessions_controller.rb
class Potepan::UserSessionsController < Devise::SessionsController
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Common
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Store

  def create
    authenticate_spree_user!

    if spree_user_signed_in?
      respond_to do |format|
        format.html do
          flash[:success] = I18n.t('spree.logged_in_succesfully')
          redirect_back_or_default(after_sign_in_path_for(spree_current_user))
        end
        format.js { render success_json }
      end
    else
      respond_to do |format|
        format.html do
          flash[:error] = t('devise.failure.invalid')
          redirect_to potepan_root_path
        end
        format.js do
          render json: { error: t('devise.failure.invalid') }, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    super
  end
end

app/views/potepan/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/potepan/shared/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= element.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_root_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= element.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/shared/_login_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <%= form_for Spree::User.new, as: :spree_user, url: potepan_create_new_session_path do |f| %>
          <div class="form-group">
            <%= f.label :email, "Enter Email" %>
            <%= f.email_field :email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password, "Password" %>
            <%= f.password_field :password, class: "form-control", tabindex: 2 %>
          </div>
          <div class="checkbox">
            <label>
              <%= f.check_box :remember_me, tabindex: 3 %> Remember Me
            </label>
          </div>
          <%= f.submit "log in", class: "btn btn-primary btn-block" %>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/potepan/shared/_partners.html.erb
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", alt: "partner-img-GUCCI") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", alt: "partner-img-D&G") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", alt: "partner-img-HERMES") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", alt: "partner-img-GIORGIO ARMANI") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img-CHANEL") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/shared/_product_quick_view_modal.erb
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>149円</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <!-- <option value="0">数</option> -->
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/potepan/shared/_signup_modal.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <%= form_for Spree::User.new, as: :spree_user, url: potepan_registration_path do |f| %>
          <div class="form-group">
            <%= f.label :email, "Enter Email" %>
            <%= f.email_field :email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password, "Password" %>
            <%= f.password_field :password, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, "Confirm Password" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>
          <%= f.submit "Sign up", class: "btn btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>