config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get root                        to: 'home#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: [:show] do
      collection do
        get 'search'
      end
    end
    resources :categories, only: [:show]
    resources :orders, only: [:show]
    get 'cart', to: 'orders#edit'
    post 'add_cart', to: 'orders#add_cart'
    patch 'cart', to: 'orders#update'
    resources :line_items, only: [:destroy]
    get 'checkout/:state', to: 'checkout#edit', as: :checkout_state
    patch 'checkout/update/:state', to: 'checkout#update', as: :update_checkout
    devise_for :spree_users, {
      class_name: 'Spree::User', controllers: {
        sessions: 'potepan/user_sessions',
        registrations: 'potepan/user_registrations',
      },
    }
    devise_scope :spree_user do
      get '/logout', to: 'user_sessions#destroy', as: :logout
      post '/login', to: 'user_sessions#create', as: :create_new_session
      post '/signup', to: 'user_registrations#create', as: :registration
    end
  end
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  # Viewでcount_number_of_productsメソッドを使えるようにする
  helper_method :count_number_of_products

  def show
    # includesで「N+1問題」を解決
    # SELECT `taxonomies`.* FROM `taxonomies` WHERE `taxonomies`.`root_id` IN (1, 2, 3, ...)
    @taxonomies = Spree::Taxonomy.includes(:root)

    @taxon = Spree::Taxon.find(params[:id])

    @option_types = Spree::OptionType.includes(:option_values)

    @products =
      if params[:color] && params[:sort]
        Spree::Product.select_by_category(@taxon).
          filter_by_option_values(filter_params[:color]).
          sort_in_order(filter_params[:sort])
      elsif params[:size] && params[:sort]
        Spree::Product.select_by_category(@taxon).
          filter_by_option_values(filter_params[:size]).
          sort_in_order(filter_params[:sort])
      elsif params[:color] && params[:size]
        colors_ids = Spree::Product.
          select_by_category(@taxon).
          filter_by_option_values(filter_params[:color]).ids
        sizes_ids = Spree::Product.
          select_by_category(@taxon).
          filter_by_option_values(filter_params[:size]).ids
        Spree::Product.where(id: colors_ids & sizes_ids)
      elsif params[:color]
        Spree::Product.select_by_category(@taxon).
          filter_by_option_values(filter_params[:color])
      elsif params[:size]
        Spree::Product.select_by_category(@taxon).
          filter_by_option_values(filter_params[:size])
      elsif params[:sort]
        Spree::Product.select_by_category(@taxon).
          sort_in_order(filter_params[:sort])
      else
        Spree::Product.select_by_category(@taxon).
          from_newest_to_oldest
      end
  end

  private

  # URLクエリをストロングパラメーターで取得
  def filter_params
    { color: params[:color], size: params[:size], sort: params[:sort] }
  end

  # Color, Sizeなどのoption_valueに応じた商品数を取得するメソッド
  def count_number_of_products(option_value)
    Spree::Product.includes(variants: :option_values).
      in_taxon(@taxon).
      where(spree_option_values: { name: option_value }).
      count
  end
end

app/controllers/potepan/checkout_controller.rb
class Potepan::CheckoutController < ApplicationController
  include Spree::Core::ControllerHelpers::StrongParameters
  include Spree::Core::ControllerHelpers::PaymentParameters
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  before_action :load_order
  before_action :set_state_if_present
  before_action :setup_for_current_state, only: [:edit, :update]

  # Updates the order and advances to the next state (when possible.)
  def update
    if update_order
      unless transition_forward
        redirect_on_failure
        return
      end

      if @order.completed?
        finalize_order
      else
        @order.next if @order.state == "delivery"
        send_to_next_state
      end

    else
      render :edit
    end
  end

  private

  def update_order
    Spree::OrderUpdateAttributes.new(@order, update_params, request_env: request.headers.env).apply
  end

  def redirect_on_failure
    flash[:error] = @order.errors.full_messages.join("\n")
    redirect_to(potepan_checkout_state_path(@order.state))
  end

  def transition_forward
    if @order.can_complete?
      @order.complete
    else
      @order.next
    end
  end

  def finalize_order
    @current_order = nil
    Spree::OrderMailer.confirm_email(@order).deliver_now
    set_successful_flash_notice
    redirect_to completion_route
  end

  def set_successful_flash_notice
    flash.notice = t('spree.order_processed_successfully')
    flash['order_completed'] = true
  end

  def send_to_next_state
    redirect_to potepan_checkout_state_path(@order.state)
  end

  def update_params
    if update_params = massaged_params[:order]
      update_params.permit(permitted_checkout_attributes)
    else
      # We currently allow update requests without any parameters in them.
      {}
    end
  end

  def massaged_params
    massaged_params = params.deep_dup

    move_payment_source_into_payments_attributes(massaged_params)
    if massaged_params[:order] && massaged_params[:order][:existing_card].present?
      Spree::Deprecation.
      warn("Passing order[:existing_card] is deprecated. Send order[:wallet_payment_source_id] instead.", caller)
      move_existing_card_into_payments_attributes(massaged_params) # deprecated
    end
    move_wallet_payment_source_id_into_payments_attributes(massaged_params)
    set_payment_parameters_amount(massaged_params, @order)

    massaged_params
  end

  # Should be overriden if you have areas of your checkout that don't match
  # up to a step within checkout_steps, such as a registration step
  def skip_state_validation?
    false
  end

  # @orderがない場合、カートページに遷移
  def load_order
    @order = current_order
    redirect_to(potepan_cart_path) && return unless @order
  end

  # params[:state]がある場合、次のステップへ進む
  def set_state_if_present
    if params[:state]
      redirect_to potepan_checkout_state_path(@order.state) if @order.can_go_to_state?(params[:state]) && !skip_state_validation?
      @order.state = params[:state]
    end
  end

  # Provides a route to redirect after order completion
  def completion_route
    potepan_order_path(@order)
  end

  def setup_for_current_state
    method_name = :"before_#{@order.state}"
    send(method_name) if respond_to?(method_name, true)
  end

  def before_address
    @order.assign_default_user_addresses
    # If the user has a default address, the previous method call takes care
    # of setting that; but if he doesn't, we need to build an empty one here
    default = { country_id: Spree::Country.default.id }
    @order.build_ship_address(default) unless @order.ship_address
  end

  def before_delivery
    return if params[:order].present?

    packages = @order.shipments.map(&:to_package)
    @differentiator = Spree::Stock::Differentiator.new(@order, packages)
  end

  def before_payment
    if @order.checkout_steps.include? "delivery"
      packages = @order.shipments.map(&:to_package)
      @differentiator = Spree::Stock::Differentiator.new(@order, packages)
      @differentiator.missing.each do |variant, quantity|
        @order.contents.remove(variant, quantity)
      end
    end

    if try_spree_current_user && try_spree_current_user.respond_to?(:wallet)
      @wallet_payment_sources = try_spree_current_user.wallet.wallet_payment_sources
      @default_wallet_payment_source = @wallet_payment_sources.detect(&:default) ||
                                       @wallet_payment_sources.first

      # TODO: How can we deprecate this instance variable?  We could try
      # wrapping it in a delegating object that produces deprecation warnings.
      @payment_sources = try_spree_current_user.wallet.wallet_payment_sources.
        map(&:payment_source).
        select { |ps| ps.is_a?(Spree::CreditCard) }
    end
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  NEW_PRODUCTS_LIMIT = 8

  def index
    # new_products scopeは、app/models/spree/product_decoratorにて定義
    @new_products = Spree::Product.includes(master: [:default_price, :images]).
      from_newest_to_oldest.limit(NEW_PRODUCTS_LIMIT)
  end
end

app/controllers/potepan/line_items_controller.rb
class Potepan::LineItemsController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def destroy
    item = Spree::LineItem.find(params[:id])
    item.order.contents.remove_line_item(item)
    redirect_to potepan_cart_path
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def show
    @order = Spree::Order.find_by(number: params[:id])
  end

  def edit
    # https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/orders_controller.rb
    @order = current_order || Spree::Order.incomplete.
      find_or_initialize_by(guest_token: cookies.signed[:guest_token])
  end

  def add_cart
    # 新しいアイテムをカートに追加
    # https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/orders_controller.rb
    @order = current_order(create_order_if_necessary: true)
    authorize! :update, @order, cookies.signed[:guest_token]

    variant  = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].to_i

    # あり得ない量が注文されてエラーが起きる防ぐために 発注の最大値を設定する
    if !quantity.between?(1, 2_147_483_647)
      @order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
    end

    # カートのアップデート時にエラーが起こった場合に、500エラーを吐かせ図にメッセージを返す
    begin
      @line_item = @order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => e
      @order.errors.add(:base, e.record.errors.full_messages.join(", "))
    end

    if @order.errors.any?
      flash[:error] = @order.errors.full_messages.join(", ")
      redirect_back_or_default potepan_root_path
      return
    else
      redirect_to potepan_cart_path
    end
  end

  def update
    @order = Spree::Order.find_by(number: params[:number])
    if @order.contents.update_cart(order_params)
      # formの送信先のnameがcheckoutの場合、次ステップに進む
      @order.next if params.key?(:checkout) && @order.cart?
      if params.key?(:checkout)
        redirect_to potepan_checkout_state_path(@order.checkout_steps.first)
      else
        redirect_to potepan_cart_path
      end
    end
  end

  private

  def order_params
    params.require(:order).permit(line_items_attributes: [:id, :quantity])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  RELATED_PRODUCTS_LIMIT = 4

  def show
    @product = Spree::Product.find(params[:id])

    # related_products scopeは、app/models/spree/product_decoratorにて定義
    @related_products = Spree::Product.related_products(@product).limit(RELATED_PRODUCTS_LIMIT)
  end

  def search
    @search_word = params[:search]
    @products = Spree::Product.search(@search_word)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/user_registrations_controller.rb
class Potepan::UserRegistrationsController < Devise::RegistrationsController
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Common
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Store

  def create
    build_resource(spree_user_params)
    if resource.save
      set_flash_message(:success, :signed_up)
      sign_in(:spree_user, resource)
      session[:spree_user_signup] = true
      respond_with resource, location: after_sign_up_path_for(resource)
    else
      clean_up_passwords(resource)
      respond_with(resource) do |format|
        flash[:error] = t('devise.failure.invalid')
        format.html { redirect_to potepan_root_path }
      end
    end
  end

  private

  def spree_user_params
    params.require(:spree_user).permit(Spree::PermittedAttributes.user_attributes | [:email])
  end
end

app/controllers/potepan/user_sessions_controller.rb
class Potepan::UserSessionsController < Devise::SessionsController
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Common
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Store

  def create
    authenticate_spree_user!

    if spree_user_signed_in?
      respond_to do |format|
        format.html do
          flash[:success] = I18n.t('spree.logged_in_succesfully')
          redirect_back_or_default(after_sign_in_path_for(spree_current_user))
        end
        format.js { render success_json }
      end
    else
      respond_to do |format|
        format.html do
          flash[:error] = t('devise.failure.invalid')
          redirect_to potepan_root_path
        end
        format.js do
          render json: { error: t('devise.failure.invalid') }, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    super
  end
end

app/views/potepan/checkout/_address.html.erb
<%= order_form.fields_for :ship_address do |address_fields| %>
  <div class="col-xs-12">
    <div class="page-header">
      <h4>入力フォーム</h4>
    </div>
  </div>
  <div class="form-group col-sm-6 col-xs-12">
    <%= address_fields.label :lastname, "姓" %>
    <%= address_fields.text_field :lastname, class: "form-control" %>
  </div>
  <div class="form-group col-sm-6 col-xs-12">
    <%= address_fields.label :firstname, "名" %>
    <%= address_fields.text_field :firstname, class: "form-control" %>
  </div>
  <div class="form-group col-sm-6 col-xs-12">
    <%= order_form.label :email, "メールアドレス" %>
    <%= order_form.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group col-sm-6 col-xs-12">
    <%= address_fields.label :zipcode, "郵便番号" %>
    <%= address_fields.text_field :zipcode, class: "form-control" %>
  </div>
  <div class="form-group col-sm-6 col-xs-12">
    <%= address_fields.label :state_id, "都道府県" %>
    <%= address_fields.collection_select :state_id, order.ship_address.country.states,
      :id, :name, {}, class: "form-control" %>
  </div>
  <div class="form-group col-sm-6 col-xs-12">
    <%= address_fields.label :city, "市町村" %>
    <%= address_fields.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group col-sm-6 col-xs-12">
    <%= address_fields.label :address1, "番地" %>
    <%= address_fields.text_field :address1, class: "form-control" %>
  </div>
  <div class="form-group col-sm-6 col-xs-12">
    <%= address_fields.label :phone, "電話番号" %>
    <%= address_fields.telephone_field :phone, class: "form-control" %>
  </div>
  <%= render "submit_button", order: order, order_form: order_form %>
<% end %>

app/views/potepan/checkout/_confirm.html.erb
<div class="col-xs-12">
  <div class="page-header">
    <h4>入力内容確認</h4>
  </div>
</div>

<div class="col-sm-12 col-xs-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">お届け先情報</h4>
    </div>
    <div class="panel-body">
      <address>
        <strong><%= order.ship_address.lastname %> <%= order.ship_address.firstname %></strong><br>
        <%= order.ship_address.zipcode %><br>
        <%= order.ship_address.state %><%= order.ship_address.city %><%= order.ship_address.address1 %><br>
      </address>
    </div>
  </div>
</div>
<div class="col-sm-6 col-xs-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">お支払い方法</h4>
    </div>
    <div class="panel-body">
      <address>
        <span>
          <% payment = order.payments.last %>
          <%= payment.payment_method.name %>
          <% if payment.payment_method.name == "Credit Card" %>
            −<%= payment.source.cc_type %> <br>
            Name: <%= payment.source.name %> <br>
            Number: <%= payment.source.display_number %>
          <% end %>
        </span>
      </address>
    </div>
  </div>
</div>
<div class="col-sm-6 col-xs-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">お届け方法</h4>
    </div>
    <div class="panel-body">
      <address>
        <% order.shipments.includes(shipping_rates: [:shipping_method]).each do |shipment| %>
          <span><%= shipment.selected_shipping_rate.name %></span>
        <% end %>
      </address>
    </div>
  </div>
</div>
<div class="col-xs-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">注文詳細</h4>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-4 col-xs-12">
          <address>
            <a href="#"><%= "Email: #{order.email}" %><br></a>
            <span><%= "Phone: #{order.ship_address.phone}" %></span>
          </address>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-xs-12">
  <div class="cartListInner">
    <%= render "potepan/orders/order_form", order: order, order_form: order_form %>
  </div>
</div>
<%= render "submit_button", order: order, order_form: order_form %>

app/views/potepan/checkout/_form_hidden.html.erb
<%= form.hidden_field :firstname %>
<%= form.hidden_field :lastname %>
<%= form.hidden_field :company %>
<%= form.hidden_field :address1 %>
<%= form.hidden_field :address2 %>
<%= form.hidden_field :city %>
<%= form.hidden_field :country_id %>
<%= form.hidden_field :state_id %>
<%= form.hidden_field :state_name %>
<%= form.hidden_field :zipcode %>
<%= form.hidden_field :phone %>
<%= form.hidden_field :alternative_phone %>

app/views/potepan/checkout/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= order.checkout_title %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_root_path %>
          </li>
          <li class="active"><%= order.checkout_title %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/checkout/_payment.html.erb
<div class="col-xs-12">
  <div class="page-header">
    <h4>お支払い方法</h4>
  </div>
  <%#= order.available_payment_methods[0].cc_type %>
  <% order.available_payment_methods.each do |payment_method| %>
    <p>
      <label>
        <%= radio_button_tag "order[payments_attributes][][payment_method_id]", payment_method.id, payment_method == order.available_payment_methods.first %>
        <%= payment_method.name %>
      </label>
    </p>
  <% end %>
</div>
<% order.available_payment_methods.each do |payment_method| %>
  <%= render "potepan/checkout/payment/#{payment_method.partial_name}", payment_method: payment_method, order: order %>
<% end %>
<%= render "submit_button", order_form: order_form, order: order %>

app/views/potepan/checkout/_progress_wizard_steps.html.erb
<div class="row progress-wizard" style="border-bottom:0;">
  <div class="col-xs-4 progress-wizard-step complete <%= "fullBar" unless order.address? %>">
    <div class="text-center progress-wizard-stepnum">お届け先情報</div>
    <div class="progress"><div class="progress-bar"></div></div>
    <i class="progress-wizard-dot"></i>
  </div>

  <div class="col-xs-4 progress-wizard-step <%= order.payment_wizard_steps %>">
    <div class="text-center progress-wizard-stepnum">お支払い方法</div>
    <div class="progress"><div class="progress-bar"></div></div>
    <i class="progress-wizard-dot"></i>
  </div>

  <div class="col-xs-4 progress-wizard-step <%= order.confirm? ? "complete" : "disabled" %>">
    <div class="text-center progress-wizard-stepnum">入力内容確認</div>
    <div class="progress"><div class="progress-bar"></div></div>
    <i class="progress-wizard-dot"></i>
  </div>
</div>

app/views/potepan/checkout/_submit_button.html.erb
<div class="col-xs-12">
  <div class="well well-lg clearfix">
    <ul class="pager">
      <% unless order.address? %>
        <li class="previous"><%= link_to "戻る", potepan_checkout_state_path(order.previous_checkout_state) %></li>
      <% end %>
      <li class="next"><%= order_form.submit order.confirm? ? "購入確定" : "次へ" %></li>
    </ul>
  </div>
</div>

app/views/potepan/checkout/edit.html.erb
<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <%= render "light_section", order: @order %>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix stepsWrapper">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="innerWrapper clearfix stepsPage">
            <%= render "progress_wizard_steps", order: @order %>
            <%= form_for @order, url: potepan_update_checkout_path(@order.state) do |order_form| %>
              <%= render @order.state, order: @order, order_form: order_form %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
<%= render "potepan/shared/login_modal" %>
<%= render "potepan/shared/signup_modal" %>